### ISSUE TITLE
Google play store 出现 DF-DFERH-01 错误

### ISSUE THREAD

**Issue by libregratis** [woniuzfb/luci-app-xray#1]
"透明代理" 中的 "代理模式" 为 CN Direct 时，
打开 Google play store 出现 DF-DFERH-01 错误，
在 Extra proxy list 添加 googleapis.com 和 googleapis.cn 依然无效；
![2021-04-24 22-54-10 的屏幕截图](https://user-images.githubusercontent.com/78979149/115963283-39778400-a551-11eb-90d0-59e2b9d4026d.png)

当代理模式切换为 GFWList Proxy 时，
运行 Google play store 一切正常，
但由于 GFWList Proxy 机制所限，github 及其他未被墙的海外网站的访问速度之慢难以忍受；

感觉  Extra proxy list 没有启用，不知道是否有办法在  CN Direct 时，能让 Google play store 正常运行
![2021-04-24 23-04-30 的屏幕截图](https://user-images.githubusercontent.com/78979149/115963340-7c395c00-a551-11eb-98fb-ffbcd8ab332b.png)

Router: Xiaomi R3G
OS: OpenWrt 19.07.7
core: openwrt-xray
luci: luci-app-v2ray
![2021-04-24 22-55-07 的屏幕截图](https://user-images.githubusercontent.com/78979149/115963297-48f6cd00-a551-11eb-9f31-b031eee5f185.png)

**Comment by woniuzfb** [comment]
resolveip googleapis.com
ipset list v2ray_dst_proxy_v4
输出正常吗

[已修复](https://github.com/woniuzfb/luci-app-xray/releases)
