### ISSUE TITLE
vless, trojan prototocl are not there in drop list

### ISSUE THREAD

**Issue by gainskills** [woniuzfb/luci-app-xray#2]
Installed the package: v2.0.0-3 on openwrt 9.07.7 r11306-c4a6851c72 by following the steps:
opkg update
opkg download dnsmasq-full
opkg remove dnsmasq
opkg install dnsmasq-full --cache .
opkg install zoneinfo-asia libustream-openssl jshn ip-full ipset iptables iptables-mod-tproxy resolveip
opkg install luci-app-v2ray_2.x.x_all.ipk --force-reinstall
opkg install luci-i18n-v2ray-zh-cn_git-xxxx_all.ipk --force-reinstall

vless, trojan prototocl are not there in drop list

![image](https://user-images.githubusercontent.com/1937472/127444065-4baaee45-1378-4a2e-ad3a-11793f5fd3d8.png)
![image](https://user-images.githubusercontent.com/1937472/127444108-edcf8eb4-59f3-4a93-818f-482b2116288b.png)

Could u please advise?
Thanks,

**Comment by 70599** [comment]
It depends on what core you are using.
Try Xray instead of V2ray.

**Comment by gainskills** [comment]
> It depends on what core you are using.
> Try Xray instead of V2ray.

Thanks a lot for your response. xray already there when I did the screenshot on the droplist. 
![image](https://user-images.githubusercontent.com/1937472/127570297-c9447ec3-c023-45f9-9c96-a8853d284748.png)

**Comment by gainskills** [comment]
have no idea what happened, the items are there without any change...
Again, thanks for your help.
